function shQuote(value: string): string {
  return value.replace(/'/g, "'\\''")
}

export function buildCliInstallScript(baseUrl: string): string {
  const origin = shQuote(baseUrl.replace(/\/+$/, ""))
  return [
    "#!/usr/bin/env sh",
    "set -eu",
    "",
    `ZAMAPAY_ORIGIN='${origin}'`,
    'BIN_DIR="${HOME}/.zamapay/bin"',
    'FROM_SOURCE=""',
    'INSTALL_AGENTS=0',
    'YES=0',
    'REMOVE=0',
    "",
    "usage() {",
    '  echo "Usage: install.sh [--from-source PATH] [--bin-dir PATH] [--agents] [--yes] [--remove]"',
    "}",
    "",
    'while [ "$#" -gt 0 ]; do',
    '  case "$1" in',
    "    --from-source)",
    '      FROM_SOURCE="${2:-}"',
    '      [ -n "$FROM_SOURCE" ] || { echo "--from-source requires a path" >&2; exit 64; }',
    "      shift 2",
    "      ;;",
    "    --bin-dir)",
    '      BIN_DIR="${2:-}"',
    '      [ -n "$BIN_DIR" ] || { echo "--bin-dir requires a path" >&2; exit 64; }',
    "      shift 2",
    "      ;;",
    "    --agents)",
    "      INSTALL_AGENTS=1",
    "      shift",
    "      ;;",
    "    --yes|-y)",
    "      YES=1",
    "      shift",
    "      ;;",
    "    --remove)",
    "      REMOVE=1",
    "      shift",
    "      ;;",
    "    --help|-h)",
    "      usage",
    "      exit 0",
    "      ;;",
    "    *)",
    '      echo "Unknown option: $1" >&2',
    "      usage >&2",
    "      exit 64",
    "      ;;",
    "  esac",
    "done",
    "",
    'if [ "$REMOVE" -eq 1 ]; then',
    '  rm -f "$BIN_DIR/zamapay"',
    '  echo "Removed $BIN_DIR/zamapay"',
    "  exit 0",
    "fi",
    "",
    'if [ "$YES" -ne 1 ]; then',
    '  echo "Pass --yes to install files." >&2',
    "  exit 64",
    "fi",
    "",
    'mkdir -p "$BIN_DIR"',
    "",
    'if [ -z "$FROM_SOURCE" ]; then',
    '  echo "Prebuilt ZamaPay CLI releases are not published yet." >&2',
    '  echo "Use: sh install.sh --from-source /path/to/zamapay --yes" >&2',
    "  exit 69",
    "fi",
    "",
    'if [ ! -d "$FROM_SOURCE/crates/cli" ]; then',
    '  echo "No crates/cli directory found under $FROM_SOURCE" >&2',
    "  exit 66",
    "fi",
    "",
    '(cd "$FROM_SOURCE" && cargo build -p zamapay-cli --release)',
    'cp "$FROM_SOURCE/target/release/zamapay" "$BIN_DIR/zamapay"',
    'chmod +x "$BIN_DIR/zamapay"',
    'echo "Installed zamapay to $BIN_DIR/zamapay"',
    "",
    'if [ "$INSTALL_AGENTS" -eq 1 ]; then',
    '  curl -fsSL "$ZAMAPAY_ORIGIN/.well-known/skills/zamapay/install.sh" | sh -s -- --yes',
    "fi",
    "",
  ].join("\n")
}

export function buildSkillInstallScript(baseUrl: string): string {
  const origin = shQuote(baseUrl.replace(/\/+$/, ""))
  return [
    "#!/usr/bin/env sh",
    "set -eu",
    "",
    `ZAMAPAY_ORIGIN='${origin}'`,
    'TARGET_DIR="${CODEX_HOME:-${HOME}/.codex}/skills/zamapay"',
    'YES=0',
    'PRINT=0',
    "",
    "usage() {",
    '  echo "Usage: install.sh [--dir PATH] [--yes] [--print]"',
    "}",
    "",
    'while [ "$#" -gt 0 ]; do',
    '  case "$1" in',
    "    --dir)",
    '      TARGET_DIR="${2:-}"',
    '      [ -n "$TARGET_DIR" ] || { echo "--dir requires a path" >&2; exit 64; }',
    "      shift 2",
    "      ;;",
    "    --yes|-y)",
    "      YES=1",
    "      shift",
    "      ;;",
    "    --print)",
    "      PRINT=1",
    "      shift",
    "      ;;",
    "    --help|-h)",
    "      usage",
    "      exit 0",
    "      ;;",
    "    *)",
    '      echo "Unknown option: $1" >&2',
    "      usage >&2",
    "      exit 64",
    "      ;;",
    "  esac",
    "done",
    "",
    'if [ "$PRINT" -eq 1 ]; then',
    '  curl -fsSL "$ZAMAPAY_ORIGIN/.well-known/skills/zamapay"',
    "  exit 0",
    "fi",
    "",
    'if [ "$YES" -ne 1 ]; then',
    '  echo "Pass --yes to install the ZamaPay Codex skill." >&2',
    "  exit 64",
    "fi",
    "",
    'mkdir -p "$TARGET_DIR"',
    'curl -fsSL "$ZAMAPAY_ORIGIN/.well-known/skills/zamapay" > "$TARGET_DIR/SKILL.md"',
    'echo "Installed ZamaPay skill to $TARGET_DIR/SKILL.md"',
    "",
  ].join("\n")
}
